// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH1Mc2eHSkssEBmtyWZkJqrY0v6xHD1ek',
    appId: '1:395320278314:web:d1a25b234e35858899b253',
    messagingSenderId: '395320278314',
    projectId: 'weather-ahmad',
    authDomain: 'weather-ahmad.firebaseapp.com',
    storageBucket: 'weather-ahmad.firebasestorage.app',
    measurementId: 'G-NGX10TESP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDucEu2lLXwSGEYhOwh45BR3AhnE3INm-E',
    appId: '1:395320278314:android:bf44e83124c8211099b253',
    messagingSenderId: '395320278314',
    projectId: 'weather-ahmad',
    storageBucket: 'weather-ahmad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfMY0OkGJZrBDxMoxuiMAQNuqfH9JZR7k',
    appId: '1:395320278314:ios:838dd841ec5e3a6199b253',
    messagingSenderId: '395320278314',
    projectId: 'weather-ahmad',
    storageBucket: 'weather-ahmad.firebasestorage.app',
    iosBundleId: 'com.example.globalweather',
  );
}
